# Generated by Django 6.0.8 on 2026-08-12 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'В обработке'), ('waiting_for_capture', 'Ожидает подтверждения'), ('succeeded', 'Успешно'), ('canceled', 'Отменён'), ('refunded', 'Возвращён')], default='pending', max_length=30),
        ),
    ]
