# Generated by Django 6.0.8 on 2026-08-13 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_enabled', models.BooleanField(default=True, verbose_name='Баннер включён')),
                ('banner_title', models.CharField(default='Скидка 20% на первый заказ', max_length=200, verbose_name='Заголовок баннера')),
                ('banner_subtitle', models.CharField(default='При заказе от 800 ₽ — доставка бесплатно', max_length=300, verbose_name='Подзаголовок баннера')),
                ('banner_button_text', models.CharField(default='Заказать', max_length=50, verbose_name='Текст кнопки')),
                ('banner_image_url', models.URLField(blank=True, null=True, verbose_name='URL изображения')),
                ('banner_link', models.URLField(blank=True, null=True, verbose_name='Ссылка с баннера')),
                ('delivery_free_threshold', models.PositiveIntegerField(default=800, verbose_name='Порог бесплатной доставки (₽)')),
                ('delivery_base_cost', models.PositiveIntegerField(default=150, verbose_name='Базовая стоимость доставки (₽)')),
                ('bonus_enabled', models.BooleanField(default=True, verbose_name='Бонусная система включена')),
                ('bonus_rate', models.DecimalField(decimal_places=2, default=5.0, max_digits=5, verbose_name='Бонусов за 100 ₽')),
                ('bonus_min_order', models.PositiveIntegerField(default=300, verbose_name='Мин. заказ для начисления бонусов (₽)')),
                ('bonus_max_percent', models.PositiveIntegerField(default=30, verbose_name='Макс. % оплаты бонусами')),
                ('notifications_enabled', models.BooleanField(default=True, verbose_name='Уведомления включены')),
                ('notification_email', models.EmailField(default='admin@navoke.ru', max_length=254, verbose_name='Email для уведомлений')),
                ('notification_order_subject', models.CharField(default='Новый заказ на сайте', max_length=200, verbose_name='Тема письма о заказе')),
                ('site_name', models.CharField(default='НаVoke', max_length=100, verbose_name='Название сайта')),
                ('contact_phone', models.CharField(default='+7 (999) 123-45-67', max_length=20, verbose_name='Телефон')),
                ('contact_email', models.EmailField(default='info@navoke.ru', max_length=254, verbose_name='Email для связи')),
                ('contact_address', models.TextField(default='пгт. Селенгинск, ул. Ленина, 10', verbose_name='Адрес')),
                ('working_hours', models.CharField(default='Пн-Чт: 10:00 — 23:00, Пт-Вс: 11:00 — 00:00', max_length=200, verbose_name='Часы работы')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Настройка сайта',
                'verbose_name_plural': 'Настройки сайта',
                'db_table': 'site_settings',
            },
        ),
    ]
