# Generated by Django 6.0.8 on 2026-08-25 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='lunch_items',
            field=models.JSONField(default=list, verbose_name='Позиции бизнес-ланча'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='lunch_title',
            field=models.CharField(default='Бизнес-ланч', max_length=200, verbose_name='Заголовок бизнес-ланча'),
        ),
    ]
