# Generated by Django 6.0.8 on 2026-08-12 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_add_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('delivery', 'Доставка'), ('pickup', 'Самовывоз')], default='delivery', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_date',
            field=models.DateField(blank=True, help_text='Желаемая дата самовывоза', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_time',
            field=models.TimeField(blank=True, help_text='Желаемое время самовывоза', null=True),
        ),
    ]
