# Generated by Django 6.0.8 on 2026-08-20 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_cartitem_unique_together_cartitem_variant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта адреса'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_lng',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота адреса'),
        ),
    ]
