name: Deploy to RelaxDev

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to RelaxDev
        env:
          RELAXDEV_TOKEN: ${{ secrets.RELAXDEV_TOKEN }}
        run: |
          curl -X POST https://api.relaxdev.ru/projects/navoke/deploy \
            -H "Authorization: Bearer $RELAXDEV_TOKEN" \
            -H "Content-Type: application/json"
