# Generated by Django 6.0.8 on 2026-08-25 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_price_product_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='LunchMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Дата')),
                ('title', models.CharField(default='Бизнес-ланч', max_length=200, verbose_name='Заголовок')),
                ('items', models.JSONField(default=list, verbose_name='Позиции меню')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'lunch_menus',
                'ordering': ['-date'],
            },
        ),
    ]
